name: Renovate

 

on:
  schedule:
    - cron: "0 * * * *"

 

jobs:
  renovate:
    runs-on: ubuntu-latest

 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v36

 

      - name: Run Renovate
        uses: renovatebot/renovate@v27
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Add any additional configuration options here
