name: Renovate
on:
  create:
    branches:
      - '*'
  pull_request:
    types:
      - labeled
    branches:
      - '*'

  schedule:
    - cron: "*/1 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

     
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
         
